Messages:
  HELP: 'help'
  NO_PERMISSION: 'no perms'
  NOT_PLAYER: 'not player'
  NOT_COMMAND: 'not command'
  NOT_INCLAN: 'not in clan'
  ALREADY_PLAYER: 'already in this clan'
  INVALID_USAGE: 'invalid usage'
  DELETE_CLAN: 'deleted clan'
  ALREADY_EXISTS: 'this clan already exists'
  CLANCHAT_ENABLED: 'chat enabled'
  CLANCHAT_DISABLED: 'chat disbaled'
  MUTED: 'muted this player'
  TOO_FEW: 'not enough arguments'
  ADD_BLOCKED: 'added a blocked world'
  REMOVE_BLOCKED: 'removed a blocked world'
  NOT_OWNER: 'not the owner'
  BAD_WORD: 'this contains a bad word and cannot be used'
  LEAVE_CLAN: 'you have left'
  ALREADY_OWNER: 'you are already the owner of this clan!'
blocked-worlds:
- 'blockedworld'
blocked-names:
- 'urmom'